# Generated by Django 5.2.7 on 2025-10-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Подписка активна'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_email',
            field=models.BooleanField(default=True, verbose_name='Email уведомления'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_inherit',
            field=models.BooleanField(default=True, verbose_name='Наследовать настройки уведомлений'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_push',
            field=models.BooleanField(default=True, verbose_name='Push уведомления'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribe_expired',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания подписки'),
        ),
    ]
