# Generated by Django 5.2.7 on 2025-11-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserService', '0003_user_base64_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Токен подтверждения email'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия токена'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Email подтвержден'),
        ),
    ]
