# Generated by Django 5.2.7 on 2025-11-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserService', '0004_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Токен сброса пароля'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия токена сброса'),
        ),
    ]
