# Generated by Django 5.2.7 on 2025-10-29 03:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Описание действия')),
                ('category', models.CharField(choices=[('subscription', 'Абонемент'), ('donation', 'Донат'), ('profile', 'Профиль'), ('rating', 'Рейтинг'), ('other', 'Другое')], max_length=20, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История пользователя',
                'verbose_name_plural': 'Истории пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
