# Generated by Django 5.2.7 on 2025-10-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='', verbose_name='Markdown контент'),
        ),
        migrations.AddField(
            model_name='post',
            name='preview_image_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на превью изображение'),
        ),
    ]
