# Generated by Django 5.2.7 on 2025-11-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentService', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='accessibility',
            field=models.CharField(choices=[('subscribers', 'Подписчикам'), ('all', 'Всем'), ('my_subscribers', 'Всем моим подписчикам')], default='all', max_length=20, verbose_name='Кому доступен для просмотра'),
        ),
    ]
