# Generated by Django 5.2.7 on 2025-10-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserService', '0002_user_is_subscribed_user_notification_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='base64_image',
            field=models.TextField(blank=True, null=True, verbose_name='Аватарка (Base64)'),
        ),
    ]
